services:
  weblint:
    image: ghcr.io/photoncody/weblint:latest
    # build: .
    container_name: weblint
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Generate a secure key with: openssl rand -hex 32
      - SECRET_KEY=${SECRET_KEY:-CHANGE_ME}
    volumes:
      - weblint_data:/data 
      # OR use bind mount below if you prefer local folder access:
      # - ./data:/data

volumes:
  weblint_data: